# Copyright 2023 The OpenVEX Authors
# SPDX-License-Identifier: Apache-2.0

name: ci-build-test

on:
  push:
    branches:
      - "main"
  pull_request:

jobs:
  build:
    name: build
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@24cb9080177205b6e8c946b17badbe402adc938f # v3.4.0

      - uses: actions/setup-go@4d34df0c2316fe8122ab82dc22947d607c0c91f9 # v4.0.0
        with:
          go-version: '1.19'
          check-latest: true
          cache: true

      - name: build
        run: make pkg

  test:
    name: test
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@24cb9080177205b6e8c946b17badbe402adc938f # v3.4.0

      - uses: actions/setup-go@4d34df0c2316fe8122ab82dc22947d607c0c91f9 # v4.0.0
        with:
          go-version: '1.19'
          check-latest: true
          cache: true

      - name: test
        run: make test
